import Head from "next/head";

export const Seo = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
};
